//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageNotificationsWebApp.Data
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Models;

    public partial class MessageNotificationsContext : DbContext
    {
        public MessageNotificationsContext()
            : base("name=MessageNotificationsContext")
        {
        }
    
        public DbSet<DeliveredMessage> DeliveredMessages { get; set; }
        public DbSet<FailedMessage> FailedMessages { get; set; }
        public DbSet<InboundMessage> InboundMessages { get; set; }
    }
}
