//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MessageNotificationsWebApp.Models;

namespace MessageNotificationsWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessageNotificationsContainer : DbContext
    {
        public MessageNotificationsContainer()
            : base("name=MessageNotificationsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InboundMessage> InboundMessages { get; set; }
        public virtual DbSet<DeliveredMessage> DeliveredMessages { get; set; }
        public virtual DbSet<FailedMessage> FailedMessages { get; set; }
    }
}
